// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpcproto/protofile.proto

package grpcproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Candidate struct {
	CandidateID          string         `protobuf:"bytes,1,opt,name=CandidateID,json=candidateID,proto3" json:"CandidateID,omitempty"`
	CandidateName        string         `protobuf:"bytes,2,opt,name=CandidateName,json=candidateName,proto3" json:"CandidateName,omitempty"`
	EligibilityList      []*Eligibility `protobuf:"bytes,3,rep,name=EligibilityList,json=eligibilityList,proto3" json:"EligibilityList,omitempty"`
	TestResultList       []*TestResult  `protobuf:"bytes,4,rep,name=TestResultList,json=testResultList,proto3" json:"TestResultList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_protofile_a6724af26f9506eb, []int{0}
}
func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (dst *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(dst, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetCandidateID() string {
	if m != nil {
		return m.CandidateID
	}
	return ""
}

func (m *Candidate) GetCandidateName() string {
	if m != nil {
		return m.CandidateName
	}
	return ""
}

func (m *Candidate) GetEligibilityList() []*Eligibility {
	if m != nil {
		return m.EligibilityList
	}
	return nil
}

func (m *Candidate) GetTestResultList() []*TestResult {
	if m != nil {
		return m.TestResultList
	}
	return nil
}

type Eligibility struct {
	EligibilityID        string   `protobuf:"bytes,1,opt,name=EligibilityID,json=eligibilityID,proto3" json:"EligibilityID,omitempty"`
	EligibilityLevel     string   `protobuf:"bytes,2,opt,name=EligibilityLevel,json=eligibilityLevel,proto3" json:"EligibilityLevel,omitempty"`
	TestIDList           []string `protobuf:"bytes,3,rep,name=TestIDList,json=testIDList,proto3" json:"TestIDList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Eligibility) Reset()         { *m = Eligibility{} }
func (m *Eligibility) String() string { return proto.CompactTextString(m) }
func (*Eligibility) ProtoMessage()    {}
func (*Eligibility) Descriptor() ([]byte, []int) {
	return fileDescriptor_protofile_a6724af26f9506eb, []int{1}
}
func (m *Eligibility) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Eligibility.Unmarshal(m, b)
}
func (m *Eligibility) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Eligibility.Marshal(b, m, deterministic)
}
func (dst *Eligibility) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Eligibility.Merge(dst, src)
}
func (m *Eligibility) XXX_Size() int {
	return xxx_messageInfo_Eligibility.Size(m)
}
func (m *Eligibility) XXX_DiscardUnknown() {
	xxx_messageInfo_Eligibility.DiscardUnknown(m)
}

var xxx_messageInfo_Eligibility proto.InternalMessageInfo

func (m *Eligibility) GetEligibilityID() string {
	if m != nil {
		return m.EligibilityID
	}
	return ""
}

func (m *Eligibility) GetEligibilityLevel() string {
	if m != nil {
		return m.EligibilityLevel
	}
	return ""
}

func (m *Eligibility) GetTestIDList() []string {
	if m != nil {
		return m.TestIDList
	}
	return nil
}

type TestResult struct {
	CategoryID           string   `protobuf:"bytes,1,opt,name=CategoryID,json=categoryID,proto3" json:"CategoryID,omitempty"`
	TestID               string   `protobuf:"bytes,2,opt,name=TestID,json=testID,proto3" json:"TestID,omitempty"`
	Result               string   `protobuf:"bytes,3,opt,name=Result,json=result,proto3" json:"Result,omitempty"`
	Score                string   `protobuf:"bytes,4,opt,name=Score,json=score,proto3" json:"Score,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestResult) Reset()         { *m = TestResult{} }
func (m *TestResult) String() string { return proto.CompactTextString(m) }
func (*TestResult) ProtoMessage()    {}
func (*TestResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_protofile_a6724af26f9506eb, []int{2}
}
func (m *TestResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestResult.Unmarshal(m, b)
}
func (m *TestResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestResult.Marshal(b, m, deterministic)
}
func (dst *TestResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestResult.Merge(dst, src)
}
func (m *TestResult) XXX_Size() int {
	return xxx_messageInfo_TestResult.Size(m)
}
func (m *TestResult) XXX_DiscardUnknown() {
	xxx_messageInfo_TestResult.DiscardUnknown(m)
}

var xxx_messageInfo_TestResult proto.InternalMessageInfo

func (m *TestResult) GetCategoryID() string {
	if m != nil {
		return m.CategoryID
	}
	return ""
}

func (m *TestResult) GetTestID() string {
	if m != nil {
		return m.TestID
	}
	return ""
}

func (m *TestResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func (m *TestResult) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

type CandidateCreateResponse struct {
	CandidateID          string   `protobuf:"bytes,1,opt,name=CandidateID,json=candidateID,proto3" json:"CandidateID,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=Status,json=status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandidateCreateResponse) Reset()         { *m = CandidateCreateResponse{} }
func (m *CandidateCreateResponse) String() string { return proto.CompactTextString(m) }
func (*CandidateCreateResponse) ProtoMessage()    {}
func (*CandidateCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_protofile_a6724af26f9506eb, []int{3}
}
func (m *CandidateCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateCreateResponse.Unmarshal(m, b)
}
func (m *CandidateCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateCreateResponse.Marshal(b, m, deterministic)
}
func (dst *CandidateCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateCreateResponse.Merge(dst, src)
}
func (m *CandidateCreateResponse) XXX_Size() int {
	return xxx_messageInfo_CandidateCreateResponse.Size(m)
}
func (m *CandidateCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateCreateResponse proto.InternalMessageInfo

func (m *CandidateCreateResponse) GetCandidateID() string {
	if m != nil {
		return m.CandidateID
	}
	return ""
}

func (m *CandidateCreateResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*Candidate)(nil), "grpcproto.Candidate")
	proto.RegisterType((*Eligibility)(nil), "grpcproto.Eligibility")
	proto.RegisterType((*TestResult)(nil), "grpcproto.TestResult")
	proto.RegisterType((*CandidateCreateResponse)(nil), "grpcproto.CandidateCreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CandidateServiceClient is the client API for CandidateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CandidateServiceClient interface {
	CreateCandidate(ctx context.Context, in *Candidate, opts ...grpc.CallOption) (*CandidateCreateResponse, error)
}

type candidateServiceClient struct {
	cc *grpc.ClientConn
}

func NewCandidateServiceClient(cc *grpc.ClientConn) CandidateServiceClient {
	return &candidateServiceClient{cc}
}

func (c *candidateServiceClient) CreateCandidate(ctx context.Context, in *Candidate, opts ...grpc.CallOption) (*CandidateCreateResponse, error) {
	out := new(CandidateCreateResponse)
	err := c.cc.Invoke(ctx, "/grpcproto.CandidateService/CreateCandidate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CandidateServiceServer is the server API for CandidateService service.
type CandidateServiceServer interface {
	CreateCandidate(context.Context, *Candidate) (*CandidateCreateResponse, error)
}

func RegisterCandidateServiceServer(s *grpc.Server, srv CandidateServiceServer) {
	s.RegisterService(&_CandidateService_serviceDesc, srv)
}

func _CandidateService_CreateCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Candidate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).CreateCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcproto.CandidateService/CreateCandidate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).CreateCandidate(ctx, req.(*Candidate))
	}
	return interceptor(ctx, in, info, handler)
}

var _CandidateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpcproto.CandidateService",
	HandlerType: (*CandidateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCandidate",
			Handler:    _CandidateService_CreateCandidate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcproto/protofile.proto",
}

func init() {
	proto.RegisterFile("grpcproto/protofile.proto", fileDescriptor_protofile_a6724af26f9506eb)
}

var fileDescriptor_protofile_a6724af26f9506eb = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xa9, 0x6d, 0x83, 0x99, 0xd0, 0x3f, 0x2c, 0xb5, 0x46, 0x0f, 0x52, 0x82, 0x87, 0xe2,
	0xa1, 0x42, 0x3d, 0x0b, 0x42, 0xeb, 0xa1, 0x28, 0x1e, 0x36, 0xde, 0x65, 0xbb, 0x1d, 0xcb, 0x42,
	0x6c, 0xca, 0xee, 0xb4, 0xe0, 0xc9, 0x2f, 0xe9, 0x07, 0x92, 0xec, 0x96, 0xcd, 0x56, 0x3c, 0x78,
	0x09, 0x99, 0xdf, 0xbc, 0xbc, 0x79, 0xc3, 0x04, 0x2e, 0xd6, 0x7a, 0x2b, 0xb7, 0xba, 0xa4, 0xf2,
	0xd6, 0x3e, 0xdf, 0x55, 0x81, 0x13, 0xfb, 0xc6, 0x62, 0xdf, 0xca, 0xbe, 0x1b, 0x10, 0xcf, 0xc4,
	0x66, 0xa5, 0x56, 0x82, 0x90, 0x8d, 0x20, 0xf1, 0xc5, 0x62, 0x9e, 0x36, 0x46, 0x8d, 0x71, 0xcc,
	0x13, 0x59, 0x23, 0x76, 0x0d, 0x1d, 0xaf, 0x78, 0x11, 0x1f, 0x98, 0x9e, 0x58, 0x4d, 0x47, 0x86,
	0x90, 0x3d, 0x40, 0xef, 0xb1, 0x50, 0x6b, 0xb5, 0x54, 0x85, 0xa2, 0xcf, 0x67, 0x65, 0x28, 0x6d,
	0x8e, 0x9a, 0xe3, 0x64, 0x3a, 0x9c, 0xf8, 0xd1, 0x93, 0x40, 0xc1, 0x7b, 0x78, 0x2c, 0x67, 0xf7,
	0xd0, 0x7d, 0x45, 0x43, 0x1c, 0xcd, 0xae, 0x20, 0x6b, 0xd0, 0xb2, 0x06, 0x67, 0x81, 0x41, 0x2d,
	0xe0, 0x5d, 0x3a, 0x12, 0x67, 0x5f, 0x90, 0x04, 0xf6, 0x55, 0xea, 0xa0, 0xf4, 0x9b, 0x75, 0x30,
	0x84, 0xec, 0x06, 0xfa, 0x61, 0x6a, 0xdc, 0x63, 0x71, 0x58, 0xaf, 0x8f, 0xbf, 0x38, 0xbb, 0x02,
	0xa8, 0xc6, 0x2f, 0xe6, 0x7e, 0xb9, 0x98, 0x03, 0x79, 0x92, 0x69, 0xd7, 0x77, 0x91, 0x2a, 0xf5,
	0x4c, 0x10, 0xae, 0x4b, 0x5d, 0x0f, 0x07, 0xe9, 0x09, 0x1b, 0x42, 0xe4, 0xdc, 0x0e, 0xf3, 0x22,
	0xe7, 0x54, 0x71, 0xe7, 0x90, 0x36, 0x1d, 0xd7, 0xce, 0x6f, 0x00, 0xed, 0x5c, 0x96, 0x1a, 0xd3,
	0x96, 0xc5, 0x6d, 0x53, 0x15, 0x59, 0x0e, 0xe7, 0xfe, 0x36, 0x33, 0x8d, 0x82, 0x90, 0xa3, 0xd9,
	0x96, 0x1b, 0xf3, 0x9f, 0xc3, 0x0e, 0x21, 0xca, 0x49, 0xd0, 0xce, 0xd8, 0x08, 0xa7, 0x3c, 0x32,
	0xb6, 0x9a, 0xbe, 0x41, 0xdf, 0x7f, 0x99, 0xa3, 0xde, 0x2b, 0x89, 0xec, 0x09, 0x7a, 0xce, 0xbf,
	0xfe, 0x73, 0x06, 0xc1, 0x5d, 0x3c, 0xbd, 0xcc, 0xfe, 0xa2, 0xc7, 0xd1, 0x96, 0x91, 0x6d, 0xdf,
	0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x7e, 0xfa, 0xf2, 0xb0, 0x02, 0x00, 0x00,
}
